## Muista todari tentti opiskelu. Graindaa siis todennäköisyyslaskentaa ja tilastotieteitä!
# ja huulion voiman armoton treenaaminen pitee aloittaa.
save_directory = "/home/mojolake/eVault/40 Writing/anvi"

